sonar.projectKey=thunderemperor99_thunderemperor99
sonar.organization=thunderemperor99
sonar.projectName=My Flask React App
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/venv/**,**/dist/**
sonar.sourceEncoding=UTF-8